### ISSUE TITLE
Expand all available record on Enter click

### ISSUE THREAD

**Issue by yauheni-nechayeu** [victorsolaya/Multiselect_Records_PCF#14]
OOB dyn365 functional allows you to see all available records in lookup field by clicking Enter button. Your control do the same but on Space button click. Is it possible to add the same functional on Enter click?

**Comment by victorsolaya** [comment]
Hi! I will develop something within the week to achieve what you are saying. I will let you know once it is done if that's ok with you. Thank you for your time!

**Comment by yauheni-nechayeu** [comment]
Thanks!

**Comment by victorsolaya** [comment]
Hi @yauheni-nechayeu Good news! I have released the latest version v1.0.03 with new improvements and one of them is the Search you were looking for!
Let me know if that works for you :D 

![image](https://user-images.githubusercontent.com/11043789/98778584-e373b180-23f2-11eb-8678-5732d4e008df.png)

**Comment by yauheni-nechayeu** [comment]
Thanks @victorsolaya but this is not exactly what I was talking about) When you open a form, put mouse cursor into search box and click Enter button, the list of values still doesn't expanded.

**Comment by victorsolaya** [comment]
Oh sorry! Thought that could work for you. I will work on it so it will be in the next release as well. Sorry for the inconvenience

**Comment by yauheni-nechayeu** [comment]
Thank you @victorsolaya ! Yes now it is working as expected!
